const postsDatabase = [
    {
        id: 1,
        title:"Test post, please ignore",
        link:'https://www.google.ca',
        description:'Check out this cool indie website I found',
        creator:'Jim',
        subgroup:'All',
        timestamp:'2023/03/21 19:05:32',
    },
    {
        id: 2,
        title:"Second test post, please ignore",
        link:'https://www.google.ca',
        description:'Check out this cool indie website I found',
        creator:'Jim',
        subgroup:'All',
        timestamp:'2023/03/21 19:05:33',
    },
    {
        id: 3,
        title:"Third test post, please ignore",
        link:'https://www.google.ca',
        description:'Check out this cool indie website I found',
        creator:'Jim',
        subgroup:'All',
        timestamp:'2023/03/21 19:05:34',
    },
    {
        id: 4,
        title:"Fourth test post, please ignore",
        link:'https://www.google.ca',
        description:'Check out this cool indie website I found',
        creator:'Jim',
        subgroup:'All',
        timestamp:'2023/03/21 19:05:35',
    },
    {
        id: 5,
        title:"Fifth test post, please ignore",
        link:'https://www.google.ca',
        description:'Check out this cool indie website I found',
        creator:'Jim',
        subgroup:'All',
        timestamp:'2023/03/21 19:05:36',
    },
    {
        id: 6,
        title:"Sixth test post, please ignore",
        link:'https://www.google.ca',
        description:'Check out this cool indie website I found',
        creator:'Jim',
        subgroup:'All',
        timestamp:'2023/03/21 19:05:37',
    },
];